<html>
    <head></head>
    <body>
        <?php 
            $a=15;
            $b=10;
            $b+=$a;
            $c=20;
            $c-=$a;
            $d=10;
            $d*=$a;
            $e=50;
            $e/=$a;
            $f=100;
            $f%=$a;
            echo "A += : ".$b."<br>"."A -= : ".$c."<br>"."A *= : ".$d."<br>"."A /= : ".$e."<br>"."A %= : ".$f."<br>";
        ?>
    </body>
</html>